# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rH0IQ9XGFk3umPMhBvYoGKD4swLmSgY
"""

import pandas as pd
import matplotlib .pyplot as plt

data=pd.read_csv("/content/mobile_sales.csv")
data

skew_value = data["Price"].skew()
print("\nSkewness Value :", round(skew_value, 4))

if skew_value > 0:
    print("Positive Skewed Distribution")

elif skew_value < 0:
    print("Negative Skewed Distribution")

else:
    print("Symmetrical Distribution")

plt.figure(figsize=(8,5))

plt.hist(data["Price"], bins=8)

plt.xlabel("Price")
plt.ylabel("Frequency")
plt.title("Monthly Profit Distribution")

plt.grid(True)

plt.show()

import matplotlib.pyplot as plt
from scipy.stats  import binom
import numpy as np
n=12
p=0.6
k=10
prob=binom.pmf(k,n,p)#shows highest possibilty is 0.06  which means 60% chance for sucess
print(prob)

x = np.arange(0, n + 1)
pmf_values = binom.pmf(x, n, p)
plt.bar(x, pmf_values, color="red", edgecolor="black", label="Binomial PMF")

# highlight k = 10
plt.bar(k, prob, color="orange", edgecolor="black", label=f"k = {k}")

plt.xlabel("Number of successes")
plt.ylabel("Probability")
plt.title(f"Binomial distribution")
plt.legend()
plt.grid(axis="y", alpha=0.3)
plt.show()

from scipy.stats import binom
n=12
p=0.6
k=10
p=binom.cdf(k,n,p)
print(p)

from scipy.stats import binom
n=20
p=0.6
k=10
p=binom.cdf(k,n,p)
print(p)

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("/content/Iris.csv")

stats.probplot(
    df["SepalLengthCm"],
    dist="norm",
    plot=plt
)

plt.title("normal  distribution QQ Plot - Iris Sepal Length")
plt.show()

df = pd.read_csv("Iris.csv")
df

df=pd.read_csv("/content/mobile_sales.csv")
df

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("/content/mobile_sales.csv")

stats.probplot(
    df["CustomerAge"],
    dist="norm",
    plot=plt
)

plt.title("QQ Plot - Customer Age")
plt.show()



import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

df = pd.read_csv("/content/mobile_sales.csv")

stats.probplot(
    df["Price"],
    dist="norm",
    plot=plt
)

plt.title("Exponential distribution QQ Plot - House Sale Price")
plt.show()